# the brand to show at various points around the site
brand: Lorry
# the base site url
base: http://localhost

# global debug mode throughout the application, should always be false in production
debug: false

# main site enabling
enable:
    site: true
    registration: true
    upload: true

# short term notices
notice:
    text:
    class: danger

clonkforge: http://clonkforge.net/user.php?usr=%d
github:
    url: https://github.com/%s
    name: ([a-zA-Z0-9][a-zA-Z0-9-]*)

# the url which maps to the asset upload dir, without trailing /
assetbase: http://localhost/assets

# the directories for different user data, should be writeable
upload:
    assets:
    assetsize: 5M
    data:
    datasize: 128M

contact:
    address: <strong>Full Name</strong>
    legal: legal@example.com
    feedback: feedback@example.com

persistence:
    dsn: mysql:host=127.0.0.1;dbname=lorry
    username: lorry
    password: lorry

mail:
    smtp-host: example.com
    smtp-port: 587
    smtp-encryption: tls
    username: lorry
    password: lorry
    from: lorry@example.com

oauth:
    google:
        id:
        secret:

    facebook:
        id:
        secret: