# the brand to show at various points around the site
brand: Lorry
# the base site url
base: http://localhost/~benedict/clonklorry

# global debug mode throughout the application, should always be false in production
debug: true

# main site enabling
enable:
    site: true
    registration: true
    upload: true

# short term notices
notice:
    text:
    class: danger

# default urls for links
clonkforge:
    url: http://clonkforge.net/user.php?usr=%d
github:
    url: https://github.com/%s
    name: ([a-zA-Z0-9][a-zA-Z0-9-]*)

# directories for user data, should be writeable
upload:
    assetsize: 5M
    datasize: 128M

# legal info (displayed on the contact page)
contact:
    address: <strong>Full Name</strong>
    legal: legal@example.com
    feedback: developer@beheh.de

# main persistence database
persistence:
    dsn: mysql:host=127.0.0.1;dbname=lorry
    username: lorry
    password: lorry

# job queue and underlying redis database
job:
    dsn: localhost

# for outgoing mails
mail:
    smtp-host: lorry.menkar.uberspace.de
    smtp-port: 587
    smtp-encryption: tls
    username: lorry-testing
    password: aewoow8vohz0caquaeyoo0tiep3theer8eixahloo6ahSh6aesoh9wiRahpafohB
    from: lorry@testing.clonklorry.org

# content delivery
cdn:
    key:
    secret:
    region: eu-central-1
    bucket: clonklorry

# oauth secrets
oauth:
    google:
        id:
        secret:

    facebook:
        id:
        secret:

# token signature
tokens:
    algorithm: sha512
    key: changeme
